# Generated by Django 2.2.4 on 2019-10-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='product_type',
            field=models.IntegerField(choices=[(1, 'Бүгд'), (2, 'Сонгосон бүтээгдэхүүнд хэрэгжинэ'), (3, 'Сонгосон бүтээгдэхүүнд хэрэгжихгүй')], default=1, verbose_name='Бүтээгдэхүүний төрөл'),
            preserve_default=False,
        ),
    ]
