# Generated by Django 2.2.4 on 2019-10-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20191015_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Хэрэгжүүлэх дараалал'),
            preserve_default=False,
        ),
    ]
