# Generated by Django 2.2.4 on 2019-10-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('promotion', '0005_auto_20191015_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='product.Product', verbose_name='Бүтээгдэхүүн'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='customer_categories',
            field=models.ManyToManyField(related_name='promotions', to='customer.CustomerCategory', verbose_name='Харилцагчийн төрөл'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='customers',
            field=models.ManyToManyField(related_name='promotions', to='customer.Customer', verbose_name='Харилцагчид'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='product_type',
            field=models.IntegerField(choices=[(1, 'Бүгд'), (2, 'Сонгосон бүтээгдэхүүнд хэрэгжинэ'), (3, 'Сонгосон бүтээгдэхүүнд хэрэгжихгүй')], null=True, verbose_name='Бүтээгдэхүүнд хэрэгжих'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='warehouses',
            field=models.ManyToManyField(related_name='promotions', to='warehouse.Warehouse', verbose_name='Агуулах'),
        ),
    ]
