# Generated by Django 2.2.4 on 2019-10-23 13:35

from django.db import migrations, models
import src.core.validate


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_auto_20191021_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Хэрэгжүүлэх дараалал'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='quantity',
            field=models.PositiveIntegerField(null=True, validators=[src.core.validate.validate_nonzero], verbose_name='Багцийн тоо хэмжээ'),
        ),
        migrations.AlterField(
            model_name='promotionproduct',
            name='quantity',
            field=models.PositiveIntegerField(null=True, validators=[src.core.validate.validate_nonzero], verbose_name='Тоо хэмжээ'),
        ),
    ]
