# Generated by Django 2.2.4 on 2019-11-19 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_auto_20191109_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='percent',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.9)], verbose_name='Хувь'),
        ),
    ]
