# Generated by Django 2.2.4 on 2019-10-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20191015_1549'),
        ('customer', '0002_auto_20191015_1549'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Харилцагч'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Ажилтан'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Захиалагдсан'), (2, 'Савлагдсан'), (3, 'Хүргэлтээр гарсан'), (4, 'Хүргэлт хийгдсэн'), (5, 'Хүлээн авсан'), (6, 'Буцаасан')], verbose_name='Төлөв'),
        ),
    ]
