# Generated by Django 2.2.4 on 2019-10-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191021_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discounted_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total',
            field=models.FloatField(),
        ),
    ]
