# Generated by Django 2.2.4 on 2019-10-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191021_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='packing_list_id',
            field=models.IntegerField(null=True),
        ),
    ]
