# Generated by Django 2.2.4 on 2019-10-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderproduct_packing_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='packing_list_id',
        ),
        migrations.AddField(
            model_name='order',
            name='packing_list_id',
            field=models.IntegerField(null=True),
        ),
    ]
