# Generated by Django 2.2.4 on 2019-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191021_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.CharField(max_length=64),
        ),
    ]
