# Generated by Django 2.2.4 on 2019-10-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191024_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='discount_package',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
