# Generated by Django 2.2.4 on 2019-11-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20191025_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['updated_at'], 'verbose_name': 'Захиалга', 'verbose_name_plural': 'Захиалгууд'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Захиалгын бүтээгдэхүүн', 'verbose_name_plural': 'Захиалгын бүтээгдэхүүнүүд'},
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='quantity_approved',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
