# Generated by Django 2.2.4 on 2019-10-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Нэр')),
                ('image', models.ImageField(upload_to='advertisement', verbose_name='Баннер зураг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('implement_type', models.IntegerField(choices=[(1, 'Бүгд'), (2, 'Харилчагчийн төрөл'), (3, 'Харилцагчид'), (4, 'Агуулах')], verbose_name='Хэрэгжүүлэх төрөл')),
                ('is_implement', models.BooleanField(default=True, verbose_name='Хэрэгжүүлэх эсэх')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхитэй')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Зассан огноо')),
                ('customer_categories', models.ManyToManyField(blank=True, related_name='advertisements', to='customer.CustomerCategory', verbose_name='Харилцагчийн төрөл')),
                ('customers', models.ManyToManyField(blank=True, related_name='advertisements', to='customer.Customer', verbose_name='Харилцагчид')),
                ('warehouses', models.ManyToManyField(blank=True, related_name='advertisements', to='warehouse.Warehouse', verbose_name='Агуулах')),
            ],
            options={
                'verbose_name': 'Сурталчилгаа',
                'verbose_name_plural': 'Сурталчилгаанууд',
                'ordering': ['-updated_at', 'id'],
            },
        ),
    ]
