# Generated by Django 2.2.4 on 2019-10-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Бүтээгдэхүүн', 'verbose_name_plural': 'Бүтээгдэхүүнүүд'},
        ),
    ]
