# Generated by Django 2.2.4 on 2019-10-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.IntegerField(unique=True, verbose_name='ИРП харилцагчийн ID')),
                ('name', models.CharField(max_length=250, verbose_name='Компанийн нэр')),
                ('flag', models.IntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхитэй')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Зассан огноо')),
            ],
            options={
                'verbose_name': 'Компани',
                'verbose_name_plural': 'Компаниуд',
                'ordering': ['-updated_at', 'id'],
            },
        ),
    ]
