# Generated by Django 2.2.4 on 2019-10-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='Утас'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_super_manager',
            field=models.BooleanField(default=False, help_text='Бүх компаний мэдээлэл харах боломжтой', verbose_name='Удирдлагын төлөв'),
        ),
    ]
