# Generated by Django 2.2.4 on 2019-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191014_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='erp_id',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
