# Generated by Django 2.2.4 on 2019-10-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20191015_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='erp_id',
            field=models.IntegerField(null=True),
        ),
    ]
