# Generated by Django 2.2.4 on 2019-10-14 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Нэр')),
            ],
            options={
                'verbose_name': 'Харилцагчийн төрөл',
                'verbose_name_plural': 'Харилцагчийн төрлүүд',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Нэр')),
                ('register_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='Байгууллагын регистерийн дугаар')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Утас')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Имэйл')),
                ('fax', models.CharField(blank=True, max_length=128, null=True, verbose_name='Факс')),
                ('addr_country', models.CharField(blank=True, max_length=128, null=True, verbose_name='Улс')),
                ('addr_city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Аймаг/Хот')),
                ('addr_district', models.CharField(blank=True, max_length=128, null=True, verbose_name='Сум/Дүүрэг')),
                ('addr_street', models.CharField(blank=True, max_length=128, null=True, verbose_name='Гудамж 1')),
                ('addr_street2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Гудамж 2')),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Уртраг')),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Өргөрөг')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Нийлүүлэгч эсэх')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Харилцагч эсэх')),
                ('is_factory', models.BooleanField(default=False, verbose_name='Үйлдвэрлэгч эсэх')),
                ('flag', models.IntegerField(verbose_name='Флаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхитэй')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Зассан огноо')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='company.Company', verbose_name='Компани')),
                ('customer_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.CustomerCategory', verbose_name='Харилцагчийн төрөл')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.Customer', verbose_name='Толгой харилцагч')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
                ('warehouses', models.ManyToManyField(blank=True, related_name='customers', to='warehouse.Warehouse', verbose_name='Агуулахууд')),
            ],
            options={
                'verbose_name': 'Харилцагч',
                'verbose_name_plural': 'Харилцагчид',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CEOInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Холбогдох ажилтан овог')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Холбогдох ажилтан нэр')),
                ('register', models.CharField(blank=True, max_length=64, null=True, verbose_name='Холбогдох ажилтан регистер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Холбогдох ажилтан имэйл')),
                ('phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Холбогдох ажилтан утас')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхитэй')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Зассан огноо')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceo_informations', to='customer.Customer', verbose_name='Харилцагч')),
            ],
        ),
    ]
