# Generated by Django 2.2.4 on 2019-10-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceoinformation',
            options={'ordering': ['-updated_at', 'id'], 'verbose_name': 'Удирдаж ажилтан', 'verbose_name_plural': 'Удирдаж ажилтнууд'},
        ),
    ]
