# Generated by Django 2.2.4 on 2020-11-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20191015_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='addr_city',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Аймаг/Хот'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='addr_country',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Улс'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='addr_district',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Сум/Дүүрэг'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='addr_street',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Гудамж 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='addr_street2',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Гудамж 2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Утас'),
        ),
    ]
